services:
  - type: web
    name: croxshare
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_SECRET
        sync: false
      - key: NEXT_PUBLIC_PUSHER_KEY
        sync: false
      - key: NEXT_PUBLIC_PUSHER_CLUSTER
        sync: false
      - key: TURN_URLS
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
